---

- name: Rolling Update
  hosts: all
  become: true
  
  tasks:
    - name: latest apache httpd package is instlled
      ansible.builtin.yum:
        name: httpd
        state: latest
      notify: restart apache
      
  handlers:
    - name: Ensure apache is restarted
      ansible.builtin.service:
        name: httpd
        state: restarted


