---
- name: Configure Nginx and HAProxy for Jenkins
  hosts: 192.168.1.71 192.168.1.85
  become: true

  tasks:
    - name: Install Nginx and HAProxy
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - haproxy

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

