---
- name: Perform Major Version Upgrade on RHEL
  hosts: 192.168.1.71
  become: true
  tasks:
    - name: Install Leapp
      dnf:
        name: leapp
        state: present

    - name: Run the Upgrade
      command: leapp upgrade
      async: 1800  # Set a timeout for the upgrade process (adjust as needed)
      poll: 0
      register: upgrade_result

    - name: Wait for Upgrade to Complete
      async_status:
        jid: "{{ upgrade_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 180
      delay: 60

    - name: Reboot the System
      command: reboot
      async: 0
      poll: 0
      when: job_result.finished

